### PR TITLE
Fallback to upos instead of to feats

### LINKED ISSUE #76: Streamline behavior when xpos/tag is None
We found that the behavior of `spacy_stanza` is different than the default spaCy behavior. 

**spaCy**

As described [here](https://spacy.io/models#design-cnn):

> The attribute_ruler maps `token.tag` to `token.pos` if there is no morphologizer ... and copies `token.pos` to `token.tag` if there is no tagger 

That seems a sensible approach. In the Spanish model `es_core_news_sm`, that means that `token.pos_ == token.tag_`.

**spacy-stanza**

The behavior in `spacy-stanza` is different, however, and does not feel right. Here, when `xpos` is not available (`tag_`), `feats` (`morph`) is used. That is unexpected and different from spaCy. Because the Spanish stanza model `es` produces `None` for `xpos` (`tag_`), all `xpos` values become `feats` (`morph`) instead of `upos` (`pos`) as is the case in spaCy. 

Here is an example:

```python
import spacy_stanza


if __name__ == '__main__':
    text = "Además se le pediría a las empresas interesadas en prestar el servicio que se hagan cargo de la señalización y la cartelería que contiene información para los usuarios."

    nlp = nlp = spacy_stanza.load_pipeline("es")
    doc = nlp(text)
    for token in doc:
        print(token.text, token.pos_, token.tag_, token.morph)
```

The offending line that does that is here. 

https://github.com/explosion/spacy-stanza/blob/a87c723a1f45b456c3488e13afb0090362016bf9/spacy_stanza/tokenizer.py#L146

My guess is that this is an oversight and not a deliberate choice. If so, I can do a quick PR and change the line to

```python
tags.append(token.xpos or token.upos or "")
```

### PR DESCRIPTION
**Pull request by BramVanroy**
This PR makes sure that the fallback for `tag_` in spacy-stanza is the same as in spaCy. Currently this is dealt with differently in `spacy-stanza` compared to spaCy. In spaCy, the attributeruler copies `pos` to `tag` in case `tag` is not defined. However, in spacy_stanza, the morphological features are used instead. That is not desirable, I think. As a user you would expect the same behavior in spaCy and spacy_stanza.

More info and examples in the linked issue https://github.com/explosion/spacy-stanza/issues/76

For reference, `spacy-udpipe` [does not have a fallback](https://github.com/TakeLab/spacy-udpipe/blob/a38cd1e1c8dc5e18def177cd21d12922da833d6f/spacy_udpipe/tokenizer.py#L115), although if you agree with the current PR I may ask TakeLab whether they want to streamline their behavior as well.

**Warning**: this PR _does_ result in a breaking change, potentially resulting in different Token.tag_ values than before

Added a test for Spanish to illustrate the issue, which currently does not have xpos.

closes #76

### CODE REVIEW

**Comment by BramVanroy** [comment]
The test that is failing is **not due to this PR**. It fails from the English language dependency labels. Probably due to new stanza models in newer versions. The right labels on stanza 1.2.3 are

```
['discourse', 'root', 'punct', 'nsubj', 'cop', 'det', 'root', 'punct']
```

AFAICT stanza models are linked to the stanza version and models may change over patches, e.g. a 1.2.3 model may be different from 1.2.2. I can't test ALL different stanza models, so I am not sure how to deal with this. Pin a very specific stanza version in setup? I'm not a big fan of that. 

Maybe we can just use the test data from [their repo](https://github.com/stanfordnlp/stanza/blob/main/stanza/tests/test_depparse.py)? Or from a sentence from the UD treebanks.

**Comment by adrianeboyd** [comment]
Try merging `upstream/master` into this?

**Comment by adrianeboyd** [comment]
Sorry, one more thing (and I can do it if you want): can you format the tests with `black`?

**Comment by adrianeboyd** [comment]
The tests are more of a sanity check than real unit tests (which is also part of why they're not packaged with the module like in our other packages). Updates here are rare enough that I'll continue to go with the lazy option of just updating the tests as necessary.

**Comment by BramVanroy** [comment]
That makes sense! Most functionality comes down to copying stanza attributes into spaCy objects,. Useful, of course, but not a lot that can go wrong with that.

**Comment by adrianeboyd** [comment]
Thanks for the PR!

**Pull request merged**
